### ISSUE TITLE
Не работает в сафари до 14 версии

### ISSUE THREAD

**Issue by fet-lains** [FreelancerLifeStyle/dynamic_adapt#12]
Добрый день. В настольном и мобильном сафари выдаёт ошибку. Прикрепил скриншот.
![2020-11-16 21 27 06](https://user-images.githubusercontent.com/62584689/99247290-d18d7680-2817-11eb-9779-f71893afe538.jpg)

**Comment by FreelancerLifeStyle** [comment]
Добрый день. Спасибо.
Попробуйте текущую версию!

**Comment by FreelancerLifeStyle** [comment]
dynamicAdapt_old.js
